# Generated by Django 3.2.4 on 2021-06-12 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweet', '0003_auto_20210612_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='sweet/images'),
        ),
    ]
