# Generated by Django 3.2.4 on 2021-06-12 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('serial', models.AutoField(primary_key=True, serialize=False)),
                ('profileImage', models.ImageField(default='defaultProfileImage.png', upload_to='profileImage')),
                ('profileAbout', models.TextField(blank=True, max_length=1000)),
                ('gender', models.CharField(blank=True, choices=[('👱🏻 Male', '👱🏻 Male'), ('🙍🏻 Female', '🙍🏻 Female')], max_length=100)),
                ('profileRelationship', models.CharField(blank=True, choices=[('😏 Single', '😏 Single'), ('😍 Comitted', '😍 Comitted')], max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
