# Generated by Django 3.2.4 on 2021-09-02 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('👱🏻 Male', '👱🏻 Male'), ('🙍🏻 Female', '🙍🏻 Female'), ('🏳\u200d🌈 LGBT', '🏳\u200d🌈 LGBT')], max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profileRelationship',
            field=models.CharField(blank=True, choices=[('😏 Single', '😏 Single'), ('😍 Comitted', '😍 Comitted'), ('👨\u200d👩\u200d\u200d Married', '👨\u200d👩\u200d Married'), ('💔 Divorced', '💔 Divorced')], max_length=100),
        ),
    ]
